"""
Django settings for ishemalink project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
from cryptography.fernet import Fernet

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = config('SECRET_KEY', default='django-insecure-*q8t4u0!y047b_ve0fj5_o61)*@-^o7l8=+@p0x2mjbgc(xt@^')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',  # JWT token blacklist
    'drf_spectacular',
    'corsheaders',
    'django_extensions',
    'django_celery_results',
    'django_filters',
    
    # Our apps
    'core',
    'domestic',
    'international',
    
    # Security apps (must be at the end)
    'axes',  # Login attempt tracking
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Login rate limiting (after AuthenticationMiddleware)
]

ROOT_URLCONF = 'ishemalink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ishemalink.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Kigali'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'


# ============================================================================
# AUTHENTICATION BACKENDS
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes for rate limiting
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
]


# ============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    # Hybrid Authentication - Session first, then JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For web dashboard
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # For mobile apps
    ],
    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Rate Limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',   # Anonymous users: 100 requests/hour
        'user': '1000/hour',  # Authenticated users: 1000 requests/hour
        'auth': '5/minute',   # Login endpoints: 5 attempts/minute (STRICT)
    },
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# ============================================================================
# API DOCUMENTATION (SWAGGER/OPENAPI)
# ============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'IshemaLink Secure API',
    'DESCRIPTION': 'Logistics and Courier Management System with Enterprise Security',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    
    # Security Schemes Documentation
    'SECURITY': [
        {'BearerAuth': []},
        {'CookieAuth': []},
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT authentication for mobile apps. Obtain token from /api/auth/token/obtain/. Include in Authorization header as: Bearer <token>'
            },
            'CookieAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Session authentication for web dashboard. Cookie set automatically after login to /api/auth/login/session/'
            }
        }
    },
}


# ============================================================================
# CORS CONFIGURATION
# ============================================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # React default
    "http://localhost:8080",      # Vue default
    "http://127.0.0.1:3000",
]


# ============================================================================
# JWT CONFIGURATION
# ============================================================================

SIMPLE_JWT = {
    # Token Lifetimes
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Short-lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Long-lived refresh token
    
    # Token Rotation
    'ROTATE_REFRESH_TOKENS': True,  # Get new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'UPDATE_LAST_LOGIN': True,  # Update last_login field on token obtain
    
    # Token Claims
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Signing
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    
    # Headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}


# ============================================================================
# SESSION CONFIGURATION (Web Dashboard)
# ============================================================================

SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)  # True in production (HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access (XSS protection)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours (auto-logout after browser close)


# ============================================================================
# CSRF PROTECTION
# ============================================================================

CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)  # True in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'


# ============================================================================
# SECURITY HEADERS
# ============================================================================

SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter in browsers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking


# ============================================================================
# DJANGO AXES (Login Rate Limiting)
# ============================================================================

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # Lock account after 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=10)  # 10-minute lockout period
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]] # Lock by user+IP combination
AXES_RESET_ON_SUCCESS = True  # Reset failed attempts on successful login


# ============================================================================
# CELERY CONFIGURATION (Async Tasks)
# ============================================================================

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Kigali'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task


# ============================================================================
# REDIS CACHE CONFIGURATION
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Different DB than Celery (DB 1)
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'ishemalink',
        'TIMEOUT': 60 * 60 * 24,  # 24 hours default
    }
}

# Cache TTL Settings
TARIFF_CACHE_TTL = 60 * 60 * 24 * 7  # 7 days for tariffs
LOCATION_CACHE_TTL = 60 * 60 * 24 * 30  # 30 days for location data


# ============================================================================
# SMS & EMAIL CONFIGURATION
# ============================================================================

# SMS Gateway Settings (simulated for now)
SMS_GATEWAY_URL = config('SMS_GATEWAY_URL', default='https://sms.example.com/send')
SMS_API_KEY = config('SMS_API_KEY', default='test-api-key')
SMS_SENDER_NAME = 'IshemaLink'

# Email Settings (console backend for testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@ishemalink.rw'




# Encryption key for sensitive fields (NID, Tax ID, etc.)
# In production: Store in environment variables!
# Generate new key: from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())
FIELD_ENCRYPTION_KEY = config(
    'FIELD_ENCRYPTION_KEY',
    default=Fernet.generate_key().decode()  # Auto-generate for development
)