[pytest]
DJANGO_SETTINGS_MODULE = ishemalink.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --no-migrations
    --reuse-db