# Generated by Django 6.0.2 on 2026-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Fully verified (phone + NID)'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_verified',
            field=models.BooleanField(default=False, help_text='National ID verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_verified_at',
            field=models.DateTimeField(blank=True, help_text='When NID was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified via OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Backup email for account recovery', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When user became fully verified', null=True),
        ),
    ]
