# Generated by Django 6.0.2 on 2026-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anonymizationrequest_dataexportrequest_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('GOV_OFFICIAL', 'Government Official')], default='CUSTOMER', max_length=15),
        ),
    ]
