# Generated by Django 6.0.2 on 2026-02-19 12:40

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=core.encryption.EncryptedCharField(blank=True, help_text='16-digit Rwanda National ID (encrypted)', max_length=255, null=True),
        ),
    ]
