# Generated by Django 6.0.2 on 2026-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='16-digit Rwanda National ID (encrypted)', max_length=255, null=True),
        ),
    ]
