# Generated by Django 5.0.1 on 2026-02-16 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('AT_HUB', 'At Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sender_phone', models.CharField(max_length=17)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=17)),
                ('origin_district', models.CharField(max_length=50)),
                ('origin_sector', models.CharField(max_length=50)),
                ('destination_district', models.CharField(max_length=50)),
                ('destination_sector', models.CharField(max_length=50)),
                ('delivery_address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=6)),
                ('description', models.TextField()),
                ('transport_mode', models.CharField(choices=[('MOTO', 'Motorcycle'), ('BUS', 'Bus')], default='MOTO', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_domestic_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='domestic.domesticshipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domesticshipment',
            index=models.Index(fields=['tracking_code'], name='domestic_do_trackin_89bfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='domesticshipment',
            index=models.Index(fields=['status'], name='domestic_do_status_175364_idx'),
        ),
        migrations.AddIndex(
            model_name='domesticshipment',
            index=models.Index(fields=['-created_at'], name='domestic_do_created_d62a6c_idx'),
        ),
    ]
