# Generated by Django 6.0.2 on 2026-02-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('districts', models.JSONField(help_text='List of districts in this zone')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DomesticTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transport_mode', models.CharField(choices=[('MOTO', 'Motorcycle'), ('BUS', 'Bus')], max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_tariffs', to='domestic.tariffzone')),
                ('origin_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_tariffs', to='domestic.tariffzone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origin_zone', 'destination_zone', 'transport_mode'], name='domestic_do_origin__f69cec_idx'), models.Index(fields=['is_active', 'effective_date'], name='domestic_do_is_acti_2b89a2_idx')],
            },
        ),
    ]
