# Generated by Django 6.0.2 on 2026-02-16 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_tariffzone_domestictariff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('manifest_type', models.CharField(choices=[('BUS_ROUTE', 'Bus Route'), ('MOTO_DELIVERY', 'Motorcycle Delivery'), ('HUB_TRANSFER', 'Hub Transfer'), ('PICKUP_ROUTE', 'Pickup Route')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('origin_district', models.CharField(max_length=50)),
                ('destination_district', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=17)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manifests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manifests', to=settings.AUTH_USER_MODEL)),
                ('shipments', models.ManyToManyField(blank=True, related_name='manifests', to='domestic.domesticshipment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manifest_number'], name='domestic_ma_manifes_dacc47_idx'), models.Index(fields=['status', 'origin_district'], name='domestic_ma_status_cfeb6a_idx'), models.Index(fields=['-created_at'], name='domestic_ma_created_a4f573_idx')],
            },
        ),
    ]
