# Generated by Django 6.0.2 on 2026-02-21 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, max_length=17)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], default='SMS', max_length=10)),
                ('event', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('SHIPMENT_PICKED_UP', 'Shipment Picked Up'), ('SHIPMENT_IN_TRANSIT', 'Shipment In Transit'), ('SHIPMENT_OUT_FOR_DELIVERY', 'Out for Delivery'), ('SHIPMENT_DELIVERED', 'Delivered'), ('SHIPMENT_CANCELLED', 'Cancelled')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('shipment_id', models.IntegerField(blank=True, null=True)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_37b3f3_idx'), models.Index(fields=['event', '-created_at'], name='notificatio_event_d9464c_idx'), models.Index(fields=['recipient_phone'], name='notificatio_recipie_72806a_idx')],
            },
        ),
    ]
